/**
 * Generates src/agent/guide.generated.ts from docs/agent-playbook.md.
 *
 * The playbook and the agent guide used to be two hand-written texts saying the
 * same thing, which is how they drifted: a rule tightened in one and stayed
 * loose in the other. Now there is one text, and this copies it.
 *
 * Run `npm run agent:guide` after editing the playbook.
 * `tests/agent-policy.test.ts` fails when the generated file is stale.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const SOURCE = "docs/agent-playbook.md";
const TARGET = "src/agent/guide.generated.ts";

/** Backticks and `${` would end the template literal we are writing into. */
const escapeForTemplateLiteral = (text: string) =>
  text.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");

export const renderGuideModule = (markdown: string): string =>
  `// GENERATED by scripts/build-agent-guide.mts from ${SOURCE}. Do not edit.\n` +
  `// Edit the playbook, then run \`npm run agent:guide\`.\n` +
  `export const AGENT_PLAYBOOK = \`${escapeForTemplateLiteral(markdown.trim())}\n\`;\n`;

export const generate = () => renderGuideModule(readFileSync(join(root, SOURCE), "utf8"));

export const currentTarget = () => readFileSync(join(root, TARGET), "utf8");

if (process.argv[1] && process.argv[1].endsWith("build-agent-guide.mts")) {
  const next = generate();
  writeFileSync(join(root, TARGET), next);
  console.log(`${TARGET}: ${next.length} chars from ${SOURCE}`);
}
