import { createContext, useContext, useEffect, useRef, type ReactNode } from "react";
import {
  Audio,
  Sequence,
  getRemotionEnvironment,
  useCurrentFrame,
  useVideoConfig,
} from "remotion";
import {
  DEFAULT_SOUND,
  resolveTemplateSfx,
  type SfxName,
  type SoundConfig,
  type TemplateSfx,
} from "./config";
import { resolveSrc } from "../player/resolve-src";
import { playSfx, preloadSfx, subscribeSfxPlayback } from "./engine";

/** Premade pack. Most cues are generated by `npm run sfx`; recorded cues carry source metadata. */
export const SFX_PACK: Record<SfxName | "type", string> = {
  pop: "/sfx/pop.wav",
  bubble: "/sfx/bubble.wav",
  tick: "/sfx/tick.wav",
  ding: "/sfx/ding.wav",
  whoosh: "/sfx/whoosh.wav",
  "keyboard-typing-natural": "/sfx/keyboard-typing-natural.wav",
  "mouse-click-press": "/sfx/mouse-click-press.wav",
  "mouse-click-release": "/sfx/mouse-click-release.wav",
  "typewriter-scissor-metallic-low": "/sfx/typewriter-scissor-metallic-low.wav",
  "typewriter-scissor-metallic-bass": "/sfx/typewriter-scissor-metallic-bass.wav",
  "typewriter-scissor-metallic-sub": "/sfx/typewriter-scissor-metallic-sub.wav",
  "typewriter-scissor-metallic": "/sfx/typewriter-scissor-metallic.wav",
  "typewriter-scissor-low": "/sfx/typewriter-scissor-low.wav",
  "typewriter-scissor-deep": "/sfx/typewriter-scissor-deep.wav",
  "typewriter-laptop": "/sfx/typewriter-laptop.wav",
  "typewriter-chiclet": "/sfx/typewriter-chiclet.wav",
  "typewriter-scissor": "/sfx/typewriter-scissor.wav",
  typewriter: "/sfx/typewriter.wav",
  "typewriter-soft": "/sfx/typewriter-soft.wav",
  "typewriter-mechanical": "/sfx/typewriter-mechanical.wav",
  "typewriter-digital": "/sfx/typewriter-digital.wav",
  "typewriter-heavy": "/sfx/typewriter-heavy.wav",
  "typewriter-thock": "/sfx/typewriter-thock.wav",
  "typewriter-steel": "/sfx/typewriter-steel.wav",
  "typewriter-slam": "/sfx/typewriter-slam.wav",
  "typewriter-button": "/sfx/typewriter-button.wav",
  "typewriter-switch": "/sfx/typewriter-switch.wav",
  "typewriter-keycap": "/sfx/typewriter-keycap.wav",
  click: "/sfx/click.wav",
  "click-crisp": "/sfx/click-crisp.wav",
  "click-round": "/sfx/click-round.wav",
  "click-glass": "/sfx/click-glass.wav",
  toggle: "/sfx/toggle.wav",
  success: "/sfx/success.wav",
  error: "/sfx/error.wav",
  notification: "/sfx/notification.wav",
  sparkle: "/sfx/sparkle.wav",
  swoop: "/sfx/swoop.wav",
  riser: "/sfx/riser.wav",
  impact: "/sfx/impact.wav",
  glitch: "/sfx/glitch.wav",
  shutter: "/sfx/shutter.wav",
  swipe: "/sfx/swipe.wav",
  drop: "/sfx/drop.wav",
  display: "/sfx/display.wav",
  type: "/sfx/typewriter.wav",
};

/** Length of each premade file; generated values match make-sfx.mjs. */
export const SFX_SECONDS: Record<SfxName | "type", number> = {
  pop: 0.14,
  bubble: 0.2,
  tick: 0.05,
  ding: 0.8,
  whoosh: 0.45,
  "keyboard-typing-natural": 5.374989,
  "mouse-click-press": 0.059365,
  "mouse-click-release": 0.069048,
  "typewriter-scissor-metallic-low": 0.13,
  "typewriter-scissor-metallic-bass": 0.15,
  "typewriter-scissor-metallic-sub": 0.17,
  "typewriter-scissor-metallic": 0.11,
  "typewriter-scissor-low": 0.12,
  "typewriter-scissor-deep": 0.14,
  "typewriter-laptop": 0.08,
  "typewriter-chiclet": 0.07,
  "typewriter-scissor": 0.09,
  typewriter: 0.08,
  "typewriter-soft": 0.07,
  "typewriter-mechanical": 0.11,
  "typewriter-digital": 0.06,
  "typewriter-heavy": 0.13,
  "typewriter-thock": 0.15,
  "typewriter-steel": 0.18,
  "typewriter-slam": 0.2,
  "typewriter-button": 0.09,
  "typewriter-switch": 0.1,
  "typewriter-keycap": 0.12,
  click: 0.08,
  "click-crisp": 0.06,
  "click-round": 0.1,
  "click-glass": 0.16,
  toggle: 0.16,
  success: 0.8,
  error: 0.5,
  notification: 0.7,
  sparkle: 0.9,
  swoop: 0.38,
  riser: 1.2,
  impact: 0.8,
  glitch: 0.34,
  shutter: 0.26,
  swipe: 0.3,
  drop: 0.4,
  display: 0.56,
  type: 0.08,
};

const SoundContext = createContext<SoundConfig>(DEFAULT_SOUND);
const PreviewSoundScopeContext = createContext<string | null>(null);

export const SoundProvider = ({
  value,
  children,
}: {
  value: SoundConfig;
  children: ReactNode;
}) => <SoundContext.Provider value={value}>{children}</SoundContext.Provider>;

export const useSound = () => useContext(SoundContext);

/** Identifies which mounted Player owns timeline SFX in multi-player views. */
export const PreviewSoundScopeProvider = ({
  scope,
  children,
}: {
  scope: string | null;
  children: ReactNode;
}) => (
  <PreviewSoundScopeContext.Provider value={scope}>
    {children}
  </PreviewSoundScopeContext.Provider>
);

export type SfxProps = {
  /** Cue name; premade names resolve from the pack, config can remap or mute. */
  cue: SfxName | string;
  /** Frame (relative to the overlay window) when the sound fires. */
  at?: number;
  /** Cue's own volume, multiplied with the config's master volume. */
  volume?: number;
  /** Fallback source when `cue` is not a premade name and config has no remap. */
  src?: string;
  /**
   * Requested playback window. Audio is trimmed or looped so it remains
   * audible for this complete timeline interval.
   */
  durationSec?: number;
};

export type MouseClickSfxProps = {
  /** Frame when physical mouse button goes down. */
  at: number;
  /** Gain shared by press and release recordings. */
  volume?: number;
  /** Time between button-down and button-up. Defaults to a quick natural click. */
  releaseDelaySec?: number;
};

type PlaybackPlan = {
  durationSec: number;
  loop: boolean;
};

/**
 * Fit a cue to timeline motion. Longer windows loop without changing keyboard
 * pitch or cadence; shorter windows trim at the exact animation boundary.
 */
export const sfxPlaybackPlan = (
  sourceSeconds: number | null,
  requestedSeconds?: number,
  unknownSourceFallbackSeconds = 1
): PlaybackPlan => {
  const duration = Math.max(
    0.001,
    requestedSeconds ?? sourceSeconds ?? unknownSourceFallbackSeconds
  );
  if (requestedSeconds === undefined) {
    return { durationSec: duration, loop: false };
  }
  if (sourceSeconds === null) {
    return { durationSec: duration, loop: true };
  }
  return {
    durationSec: duration,
    loop: duration > sourceSeconds,
  };
};

const resolve = (
  cue: string,
  override: string | false | undefined,
  src: string | undefined
): { src: string; seconds: number | null } | null => {
  if (override === false) return null;
  const name = (typeof override === "string" ? override : cue) as SfxName | "type";
  if (SFX_PACK[name]) return { src: SFX_PACK[name], seconds: SFX_SECONDS[name] };
  const custom = typeof override === "string" ? override : src;
  return custom ? { src: custom, seconds: null } : null;
};

/**
 * Declarative sound cue. Templates drop one wherever something appears;
 * the spec's sound config decides what (and whether) it plays.
 * Renders nothing visual, safe inside any layout.
 *
 * Two playback paths:
 * - Rendering (CLI/Lambda): a real <Audio> inside a trimmed <Sequence>, so the
 *   sound is part of the encoded file.
 * - Player preview: the Web Audio engine (src/sound/engine.ts) fires when the
 *   playhead crosses `at`. No <audio> tags involved: the Player's shared
 *   AudioContext auto-mute bug (resume >1s => permanent self-mute) and
 *   Chrome's WebMediaPlayer cap can't touch these cues.
 */
export const Sfx = ({ cue, at = 0, volume = 1, src, durationSec }: SfxProps) => {
  const config = useSound();
  const previewSoundScope = useContext(PreviewSoundScopeContext);
  const { fps, durationInFrames } = useVideoConfig();
  const frame = useCurrentFrame();
  const { isRendering } = getRemotionEnvironment();
  const prevFrame = useRef<number | null>(null);
  const frameRef = useRef(frame);
  frameRef.current = frame;

  const resolved = config.enabled ? resolve(cue, config.sounds[cue], src) : null;
  const gain = Math.max(0, Math.min(1, volume * config.volume));
  const atFrame = Math.max(0, Math.round(at));
  const active = !isRendering && resolved !== null && gain > 0;
  const resolvedSrc = resolved ? resolveSrc(resolved.src) : undefined;
  // Unknown custom-file duration: leave its Sequence open through the overlay
  // instead of silently truncating it after one second. Media ends naturally.
  const availableSeconds = Math.max(1 / fps, (durationInFrames - atFrame) / fps);
  const playback = sfxPlaybackPlan(
    resolved?.seconds ?? null,
    durationSec,
    availableSeconds
  );

  useEffect(() => {
    if (!isRendering && resolvedSrc && gain > 0) preloadSfx(resolvedSrc);
  }, [gain, isRendering, resolvedSrc]);

  useEffect(() => {
    if (!active || !resolvedSrc) return;
    return subscribeSfxPlayback((playing, activeScope) => {
      if (!playing || activeScope !== previewSoundScope) return;
      const elapsedFrames = frameRef.current - atFrame;
      const playbackFrames = Math.ceil(playback.durationSec * fps);
      if (elapsedFrames < 0 || elapsedFrames >= playbackFrames) return;
      const elapsedSec = elapsedFrames / fps;
      playSfx(resolvedSrc, gain, {
        durationSec: Math.max(1 / fps, playback.durationSec - elapsedSec),
        loop: playback.loop,
        offsetSec: elapsedSec,
        scope: previewSoundScope,
      });
    });
  }, [
    active,
    resolvedSrc,
    atFrame,
    gain,
    playback.durationSec,
    playback.loop,
    fps,
    previewSoundScope,
  ]);

  useEffect(() => {
    if (!active || !resolvedSrc) return;
    const prev = prevFrame.current;
    prevFrame.current = frame;
    if (prev === null) {
      // Freshly (re)mounted: the overlay's Sequence remounts on every loop.
      if (frame === atFrame) {
        playSfx(resolvedSrc, gain, { ...playback, scope: previewSoundScope });
      }
      return;
    }
    if (prev === frame) return;
    const wrapped = frame < prev; // player looped within our window
    const smallStep = wrapped ? frame <= 3 : frame - prev <= 3; // ignore seeks
    const crossed = wrapped ? atFrame <= frame : prev < atFrame && frame >= atFrame;
    if (smallStep && crossed) {
      playSfx(resolvedSrc, gain, { ...playback, scope: previewSoundScope });
    }
  }, [
    active,
    resolvedSrc,
    frame,
    atFrame,
    gain,
    playback.durationSec,
    playback.loop,
    previewSoundScope,
  ]);

  if (!resolved || gain === 0) return null;

  if (isRendering) {
    const playbackFrames = Math.max(1, Math.ceil(playback.durationSec * fps));
    return (
      <Sequence
        from={atFrame}
        durationInFrames={playbackFrames + 1}
        layout="none"
      >
        <Audio
          src={resolvedSrc}
          volume={
            playback.loop
              ? (audioFrame) => (audioFrame <= playbackFrames ? gain : 0)
              : gain
          }
          loopVolumeCurveBehavior="extend"
          {...(playback.loop ? { loop: true } : {})}
        />
      </Sequence>
    );
  }
  return null;
};

/**
 * A cue named by a template PROP (`templateSfx`) rather than hardcoded in the
 * template: renders nothing when the caller passed `false`, plays the premade
 * cue, the bundled library file, or the caller's own audio otherwise.
 *
 * Every template routes its own sounds through this, so "can I change this
 * sound?" has exactly one answer everywhere instead of one per template.
 */
export const PropSfx = ({
  sfx,
  ...rest
}: { sfx: TemplateSfx } & Omit<SfxProps, "cue" | "src">) => {
  const resolved = resolveTemplateSfx(sfx);
  if (!resolved) return null;
  return <Sfx cue={resolved.cue} src={resolved.src} {...rest} />;
};

/** Real mouse-button press followed by its matching release. */
export const MouseClickSfx = ({
  at,
  volume = 1,
  releaseDelaySec = 0.067,
}: MouseClickSfxProps) => {
  const { fps } = useVideoConfig();
  const releaseAt = at + Math.max(1, Math.round(releaseDelaySec * fps));

  return (
    <>
      <Sfx cue="mouse-click-press" at={at} volume={volume} />
      <Sfx cue="mouse-click-release" at={releaseAt} volume={volume} />
    </>
  );
};
